# Generated by Django 4.2.6 on 2023-11-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
