# Generated by Django 4.2.6 on 2023-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='photo',
            field=models.ImageField(upload_to='media/recipes'),
        ),
        migrations.AlterField(
            model_name='story',
            name='photo',
            field=models.ImageField(upload_to='media/story'),
        ),
    ]
