# Generated by Django 4.2.6 on 2023-10-27 15:37

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_receipe_photo_alter_story_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='body',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='small_description',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]
