# Generated by Django 4.2.6 on 2023-10-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_body_story_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_story', to='stories.story'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent', to='stories.comment'),
        ),
    ]
