# Generated by Django 4.2.6 on 2023-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_rename_tag_story_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='storycategory',
            options={'verbose_name': 'Story Category', 'verbose_name_plural': 'Story Categories'},
        ),
        migrations.AddField(
            model_name='receipe',
            name='small_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
